# Generated by Django 3.1.7 on 2021-08-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20210818_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ip',
            field=models.CharField(max_length=15),
        ),
    ]
