# Generated by Django 3.2.7 on 2021-09-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_holder',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='serial',
            name='value',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
