# Generated by Django 4.0.6 on 2023-06-14 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0006_auto_20210922_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='guestbook',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestbook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='result',
            field=models.IntegerField(choices=[(1, '성공'), (0, '실패')]),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
